config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'items/index'
  root to: "items#index"
  resources :items do
    collection do
      get 'search'
    end
    resources :orders, only: [:index, :create]
    resources :comments, only: :create
  end
  resources :users, only: [:index, :show]
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :shipping_fee
  belongs_to :region
  belongs_to :eta
  belongs_to :user
  has_one :order
  has_one_attached :image
  has_many :comments, dependent: :destroy

  with_options presence: true do
    validates :product
    validates :description
    validates :states
    validates :shipping_fee_id, numericality: { other_than: 1, message: 'を選んで下さい' }
    validates :region_id, numericality: { other_than: 1, message: 'を選んで下さい' }
    validates :eta_id, numericality: { other_than: 1, message: 'を選んで下さい' }
    validates :price, format: { with: /\A[0-9]+\z/ }, numericality: { only_integer: true,
                                                                      greater_than: 0, less_than: 10_000_000 }
    validates :image
  end

  def self.search(search)
    if search != ''
      Item.where('product LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]
  PER = 4

  def index
    @items = Item.order('created_at DESC')
    @items = Item.page(params[:page]).per(PER)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def search
    @items = Item.search(params[:keyword])
  end

  private

  def item_params
    params.require(:item).permit(:product, :description, :states, :shipping_fee_id, :region_id, :eta_id, :price,
                                 :image).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index if @item.user_id != current_user.id || @item.order.present?
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>
<%= render "shared/third-header" %>
<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
       <div id="image-list"></div> 
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :product, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :states, class:"items-text", id:"item-sales-status", placeholder:"商品の状態（必須 1,000文字まで)" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_fee_id, ShippingFee.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:region_id, Region.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:eta_id, Eta.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥1〜9,999,999)</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
      </div>
    </div>
    <%# /販売価格 %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', item_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>
<% render "shared/footer" %>

app/views/items/index.html.erb
<%= render "shared/header" %>

<%# 商品一覧 %>
<div class='main'>
  <div class='item-contents'>
    <h2 class='title'>商品一覧</h2>
    <ul class='item-lists'>
      <% @items.each do |item| %>
        <li class='list'>
          <%= link_to item_path(item.id) do %>
          <div class='item-img-content'>
            <%= image_tag item.image, class: "item-img" %>
            <% if item.order.present? %>
              <div class='sold-out'>
                <span>売り切れ!!</span>
              </div>
            <% end %>
          </div>
          <div class='item-info'>
            <h3 class='item-name'>
              <%= "#{item.product}" %>
            </h3>
            <div class='item-price'>
              <span><%= "#{item.price}" %>円<br><%= "#{item.shipping_fee.name}" %></span>
            </div>
          </div>
          <% end %>
        </li>
      <% end %>
      <% if @items.length == 0 %>
        <li class='list'>
          <%= link_to '#' do %>
          <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %>
            <div class='item-info'>
              <h3 class='item-name'>
                  商品を出品してださい。
              </h3>
              <div class='item-price'>
                <span>99999999円<br>(税込み)</span>
              </div>
            </div> 
          <% end %>
        </li>
      <% end %>
    </ul>
    
    <%= paginate @items, class: 'page' %>
 
  </div>
</div>
<%# /商品一覧 %>

<%= link_to(new_item_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>出品する</span>
  <%= image_tag 'トマトのフリーアイコン.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>

<% time = Time.now # Thu Dec 24 00:00:00 +0900 2011  %>
<%= time.strftime('%Y年%m月%d日 %H:%M:%S') %>

<%= render "shared/footer" %>

app/views/items/new.html.erb
<%= render "shared/third-header" %>

<div class="items-sell-contents"> 
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>
    
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルを選択
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
      <div id="image-list"></div> 
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :product, class:"items-text", id:"item-name", placeholder:"商品名（ 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（ 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <div class="items-detail">
      <div class="form">
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :states, class:"items-text", id:"item-sales-status", placeholder:"商品の状態（ 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
        
      </div>
    </div>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_fee_id, ShippingFee.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:region_id, Region.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:eta_id, Eta.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥1〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
      </div>
    </div>
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/items/search.html.erb
<%= render "shared/third-header" %>

<div class="items-search"> 
 <div class="items-search-main">
   <% @items.each do |item| %>
      <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>
        </div>
        <div class='search-info'>
          <h3 class='item-name'>
            <%= "#{item.product}" %>
          </h3>
          <div class='item-price'>
            <span><%= "#{item.price}" %>円<br><%= "#{item.shipping_fee.name}" %></span>
          </div>
        </div>
      <% end %>
   <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/items/show.html.erb
<%= render "shared/second-header" %>

<div class="item-show">
  <%= form_with(url: search_items_path, local: true, method: :get, class: "second-search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "キーワードから探す", class: "second-input-box" %>
    <%= form.submit "検索", class: "second-search-icon" %>
  <% end %>
  <div class="item-box">
    <div class="item-image">
      <h2 class="name">
        <%= "#{@item.product}" %>
      </h2>
      <div class="item-img-content">
        <%= image_tag @item.image ,class:"item-box-img" %>
        <% if @item.order.present? %>
        <div class="sold-out">
          <span>売り切れ!!</span>
        </div>
        <% end %>
      </div>
    </div>
    <div class="item-info">
      <div class="item-price-box">
        <span class="item-price">
          <%= "¥#{@item.price}" %>
        </span>
        <span class="item-postage">
          <%= "#{@item.shipping_fee.name}" %>
        </span>
      </div>
      <div class="item-btn">
        <% if user_signed_in? && @item.order == nil %>
          <% if current_user.id == @item.user_id %>
            <%= link_to "商品の編集", edit_item_path(@item.id), method: :get, class: "item-edit-btn" %>
            <p class="or-text">or</p>
            <%= link_to "削除", item_path(@item.id), method: :delete, class:"item-destroy-btn" %>
          <% else %>
            <%= link_to "購入画面に進む", item_orders_path(@item.id) ,class:"item-buy-btn"%>
          <% end %> 
        <% end %>
      </div>
      <div class="item-explain-box">
        <span><%= "#{@item.description}" %></span>
      </div>
      <table class="detail-table">
        <tbody>
          <tr>
            <th class="detail-item">出品者</th>
            <td class="detail-value"><%= link_to "#{@item.user.store}","/users/#{@item.user.id}" %></td>
          </tr>
          <tr>
            <th class="detail-item">商品の状態</th>
            <td class="detail-value"><%= "#{@item.states}" %></td>
          </tr>
          <tr>
            <th class="detail-item">配送料の負担</th>
            <td class="detail-value"><%= "#{@item.shipping_fee.name}" %></td>
          </tr>
          <tr>
            <th class="detail-item">発送元の地域</th>
            <td class="detail-value"><%= "#{@item.region.name}" %></td>
          </tr>
          <tr>
            <th class="detail-item">発送日の目安</th>
            <td class="detail-value"><%= "#{@item.eta.name}" %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="comment-box">
    <% if user_signed_in? %>
      <%= form_with(model: [@item, @comment], local: true, id:"new-comment") do |form| %>
        <%= form.text_area :text, class: 'comment-text', rows: "2" %>
        <%= form.submit "コメント送信", class: 'comment-btn', value: "コメントする" %>
      <% end %>
    <% else %>
      <strong>
        <p>※※ コメントの投稿には新規登録/ログインが必要です ※※</p>
      </strong>
    <% end %>
      <div class="comments">
        <h4>＜コメント一覧＞</h4>
        <% @comments.each do |comment| %>
          <p>
            <%= "#{comment.user.store}" %>:
            <%= comment.text %>
          </p>
        <% end %>
      </div>
  </div>
</div>

<%= render "shared/footer" %>